{
 "title": "Cost Report",
 "time": { "from": "now-11h", "to": "now" },
 "templating": {
  "list": [
   { "name": "promdatasource", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "cwdatasource", "label": "Croudwatch Datasource", "query": "cloudwatch" },
   { "name": "region", "query": "eu-west-1" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name!=\"<none>\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name!=\"<none>\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name!=\"<none>\", namespace=\"$namespace\", pod=\"$pod\"}, node)"
    }
   },
   {
    "name": "type",
    "label": "Instance Type",
    "query": {
     "query": "label_values(kube_node_labels, label_beta_kubernetes_io_instance_type) "
    }
   },
   { "name": "cpu_cost", "label": "CPU Cost", "query": "20" },
   { "name": "memory_cost", "label": "Memory Cost", "query": "3" },
   { "name": "onDemandm44xlarge", "label": "On Demand 4x.xlarge", "query": "0.888" },
   { "name": "spotm44xlarge1a", "label": "spot 4x.xlarge1a", "query": "0.3556" },
   { "name": "spotm44xlarge1b", "label": "spot 4x.xlarge1b", "query": "0.3254" },
   { "name": "onDemandm4xlarge", "label": "On Demand m4.xlarge", "query": "0.222" },
   { "name": "spotm4xlarge", "label": "Spot m4.xlarge", "query": "0.0745" },
   { "name": "onDemandm54xlarge", "label": "On Demand m5.4xlarge", "query": "0.856" },
   { "name": "spotm54xlarge", "label": "Spot m5.4xlarge", "query": "0.3117" },
   { "name": "onDemandm5a4xlarge", "label": "On Demand m5a.4xlarge", "query": "0.768" },
   { "name": "spotm5a4xlarge1a", "label": "spotm5a4xlarge1a", "query": "0.3962" },
   { "name": "spotm5a4xlarge1c", "label": "Spot m5a.4xlarge", "query": "0.5464" },
   { "name": "onDemandm5axlarge", "label": "On Demand m5a.xlarge", "query": "0.192" },
   { "name": "spotm5axlarge", "label": "Spot m5a.xlarge", "query": "0.10148148148" },
   { "name": "onDemandt3xlarge", "label": "On Demand t3.xlarge", "query": "0.182 " },
   { "name": "spott3xlarge", "label": "Spot t3.xlarge", "query": "0.0613" },
   { "name": "onDemandt3axlarge", "label": "On Demand t3a.xlarge", "query": "0.163 " },
   { "name": "spott3axlarge", "label": "Spot t3a.xlarge", "query": "0.0628" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_eks_amazonaws_com_capacity_type=\"SPOT\"}) by (label_beta_kubernetes_io_instance_type)"
    }
   ]
  },
  {
   "title": "Cluster Cost per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum_over_time((\n    \n    sum by (label_beta_kubernetes_io_instance_type) (sum by (label_topology_kubernetes_io_zone, label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (kube_node_labels{job=\"kube-state-metrics\"}) * on (label_topology_kubernetes_io_zone, label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) sum by (label_topology_kubernetes_io_zone, label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (instance_cost))\n\n)[1d:1h])",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}"
    },
    {
     "expr": "sum(\n    sum_over_time((sum by (label_beta_kubernetes_io_instance_type) (sum by (label_topology_kubernetes_io_zone, label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (kube_node_labels{job=\"kube-state-metrics\"}) * on (label_topology_kubernetes_io_zone, label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) sum by (label_topology_kubernetes_io_zone, label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (instance_cost))\n)[1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total[30m]))/(1024*1024*1024)",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(irate(container_network_transmit_bytes_total[30m]))[$__range:])/(1024*1024*1024)*0.07",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "PV Storage",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum (sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes/1024/1024/1024))",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes/1024/1024/1024) * 0.089)"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum ((sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (node)) * on (node ) group_left(label_beta_kubernetes_io_instance_type,label_topology_kubernetes_io_zone) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node, label_topology_kubernetes_io_zone))by (label_beta_kubernetes_io_instance_type,node,label_topology_kubernetes_io_zone)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_topology_kubernetes_io_zone}} - {{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ((sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (node)) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,node) * ${cpu_cost}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum ((sum(container_memory_working_set_bytes{namespace=~\"$namespace\", name!=\"\"}) by (node) ) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,node)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{node}} "
    }
   ]
  },
  {
   "title": "Memory Cost Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ((sum(container_memory_working_set_bytes{namespace=~\"$namespace\", name!=\"\"}) by (node) ) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,node)* ${memory_cost}",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{node}} "
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum ((sum(irate(container_network_transmit_bytes_total{namespace=~\"argo\"}[30m])) by (node)  ) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,node)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{node}}  "
    }
   ]
  },
  {
   "title": "PV Storage",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum (sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024))",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024) * 0.089)"
    }
   ]
  },
  { "title": "Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum (sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"argo\"}) by (pod,node) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,pod)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum ((sum(container_memory_working_set_bytes{namespace=\"$namespace\", name!=\"\"}) by (pod,node) ) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,node,pod)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{pod}} "
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum ((sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[30m])) by (pod,node)  ) * on (node ) group_left(label_beta_kubernetes_io_instance_type) sum(kube_node_labels) by (label_beta_kubernetes_io_instance_type,node))by (label_beta_kubernetes_io_instance_type,node,pod)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{pod}}  "
    }
   ]
  },
  {
   "title": "PV Storage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024)",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024) * 0.089"
    }
   ]
  }
 ]
}