{
 "title": "Exec Kubernetes Cost Report",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Cost ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    (\n    capacity_instance:spot_instance_cost:cost \n    OR \n    capacity_instance:on_demand_instance_cost:cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "Estimated Monthly Cost (Based on last 3 Days)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    (\n    capacity_instance:spot_instance_cost:cost \n    OR \n    capacity_instance:on_demand_instance_cost:cost\n    )\n  [3d:1h])\n)*10",
     "legendFormat": "Cost"
    }
   ]
  },
  { "title": "Namespace Resources Requested", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Top 6 Resource Requests Daily Cost ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(6,\n  sum_over_time(\n      sum by (namespace) (\n          # See description for label_replace\n          label_replace(\n            zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n          , \"resource\", \"CPU\", \"\",\"\")\n          \n          OR \n          \n          label_replace(\n            zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n          , \"resource\", \"memory\", \"\",\"\")\n\n    )\n  [1d:1h])\n)"
    }
   ]
  },
  {
   "title": "Top 6 CPU Resource Requests Daily Cost ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(6,\n  sum_over_time(\n      sum by (namespace) (\n        zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n        OR\n        capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n    )\n  [1d:1h])\n)"
    }
   ]
  },
  {
   "title": "Top 6 Memory Requests Daily Cost ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(6,\n  sum_over_time(\n      sum by (namespace) (        \n        zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n        OR\n        capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n    )\n  [1d:1h])\n)"
    }
   ]
  },
  {
   "title": "Top 10 Resource Requests Daily Cost per Pod",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\nsum_over_time(\n    sum by (pod) (\n        # See description for label_replace\n        label_replace(\n\t\t    zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n        , \"resource\", \"CPU\", \"\",\"\")\n        \n        OR \n        \n        label_replace(\n\t\t    zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n        , \"resource\", \"memory\", \"\",\"\")\n\n\t)\n[1d:1h])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 6 Disk Monthly Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(6,sum by (namespace) (sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes/1024/1024/1024) * 0.089))"
    }
   ]
  },
  {
   "title": "Namespace Resources Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 6 Usage Daily Cost ",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "topk(6,\n  sum_over_time(\n      sum by (namespace) (\n          # See description for label_replace\n          label_replace(\n          zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n              OR\n              capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n          , \"resource\", \"CPU\", \"\",\"\")\n          \n          OR \n          \n          label_replace(\n          zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n              OR\n              capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost\n          , \"resource\", \"memory\", \"\",\"\")\n\n    )\n  [1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Top 6 CPU Usage Daily Cost ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "topk(6,\n  sum_over_time(\n      sum by (namespace) (\n          zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n          OR\n          capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n    )\n  [1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Top 6 Memory Usage Daily Cost ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "topk(6,\n  sum_over_time(\n      sum by (namespace) (\n          zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n          OR\n          capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost\n    )\n  [1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Top 10 Usage Daily Cost per Pod",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "topk(10,\n  sum_over_time(\n      sum by (pod) (\n          # See description for label_replace\n          label_replace(\n          zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n              OR\n              capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n          , \"resource\", \"CPU\", \"\",\"\")\n          \n          OR \n          \n          label_replace(\n          zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n              OR\n              capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost\n          , \"resource\", \"memory\", \"\",\"\")\n\n    )\n  [1d:1h])\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}