name: Helm Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/kubernetes-cost-report/Chart.yaml'
      - 'charts/kubernetes-cost-report/**/*'

env:
  HELM_VERSION: "v3.5.3"

jobs:
  helm-release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Checkout main branch"
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          fetch-depth: 0

      - name: "Configure Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: "Install Helm"
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1
        with:
          version: "${{ env.HELM_VERSION }}"

      - name: "Run chart-releaser"
        uses: helm/chart-releaser-action@c25b74a986eb925b398320414b576227f375f946 # v1.2.1
        with:
          charts_dir: charts
          charts_repo_url: https://empathyco.github.io/kubernetes-cost-report/
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"

