name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@274ee49538d9c31dcac422b27ba0b499d65a471c # v1.0.3
        with:
          working_directory: terraform
          github_token: ${{ secrets.GITHUB_TOKEN }}